title = "Toma Nistor - San Diego Web Developer"
baseURL = "https://tomanistor.com"
tags = ["web developer", "San Diego web developer", "ruby on rails developer", "javascript developer", "vuejs developer", "hugo developer", "San Diego", "web developer portfolio"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-70206008-1"
disqusShortname = "tomanistor"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies
enableRobotsTXT = true

[Params]
  tagline = "Toma Nistor"
  author = "Toma Nistor"
  description = "Full-stack web developer and UI/UX enthusiast based in San Diego, CA. I enjoy using multiple tools to engineer and build powerful websites and apps."
  logoBig = "/images/logo/Toma-Nistor-Logo-450px.png"
  logoSmall = "/images/logo/Toma-Nistor-Logo-150px.png"
  favicon = "favicon.ico"
  opengraphImage = "/images/logo/Toma-Nistor-Logo-Banner-Dark.png"
  email = "toma@tomanistor.com"
  googleTagManager = "GTM-T94X59P"
  customCSS = true

  # Social media links in footer
  twitter = "TomaNistor"
  linkedin = "tomanistor"
  github = "tomanistor"
  facebook = ""

  # Copyright and theme author credit in footer
  copyright = false
  credit = false

  # Cache busting of static resources (additional set up required)
  cacheBustCSS = true
  cacheBustJS = true

  # Code highlighting with highlight.js
  highlightJS = true
  highlightJSStyle = "" # For custom highlight.js styles, add your /path/to/styles/default.css
  highlightJSScript = "/scripts/highlight.pack.js" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

  # Choose either Formspree contact form or Basin contact form
  ajaxFormspree = true
  ajaxFormspreeGold = true # If you have a paid Formspree account and want an AJAX form
  ajaxBasin = false

# [permalinks]
#   gallery = "/" # Redirect gallery index to home page

[[menu.main]]
  name = "About"
  url  = "/#about"
  weight = 1
[[menu.main]]
  name = "Work"
  url  = "/#work"
  weight = 2
[[menu.main]]
  name = "Blog"
  url  = "/#blog"
  weight = 3
[[menu.main]]
  name = "Contact"
  url  = "/#contact"
  weight = 4
