title = "Toma Nistor"
baseURL = "https://tomanistor.com"
tags = ["portfolio", "web design", "web developer", "ruby on rails", "javascript", "postgres", "San Diego"]
languageCode = "en-US"
config = "config.toml"
theme = "outrun"
canonifyurls = true
googleAnalytics = "UA-70206008-1"

[Params]
    author = "Toma Nistor"
    description = "Full-stack web developer and UI/UX enthusiast based in San Diego, CA. I enjoy using multiple tools to engineer and build powerful websites and apps."
    logoBig = "/images/logo/Toma-Nistor-Logo-450px.png"
    logoSmall = "/images/logo/Toma-Nistor-Logo-150px.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/logo/Toma-Nistor-Logo-Banner-Dark.png"
    twitter = "TomaNistor"
    linkedin = "tomanistor"
    github = "tomanistor"
    email = "toma@tomanistor.com"
    googleTagManger = "GTM-T94X59P"
    highlightJS = true
    copyright = false
    credit = false

[[menu.main]]
    name = "Work"
    url  = "/#work"
    weight = 1
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 2
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 3
